.TH MANGLER "1" "January 2013" "mangler 1.2.5"
.SH NAME
mangler \- a Ventrilo compatible client for Linux
.SH SYNOPSIS
.B mangler
[\fB\-s\fR \fIhostname:port\fR]
[\fB\-u\fR \fIusername\fR]
[\fB\-p\fR \fIpassword\fR]
.SH DESCRIPTION
\fBmangler\fR is an open source VOIP client capable of connecting to
Ventrilo 3.x servers. It is capable of performing almost all standard user
functionality found in a Windows Ventrilo client.
.PP
.SH OPTIONS
.TP
\fB\-s\fR \fIhostname:port\fR
Specify hostname and port of the server for Mangler to connect to.
.TP
\fB\-u\fR \fIusername\fR
Specify username for Mangler to use.
.TP
\fB\-p\fR \fIpassword\fR
Specify password for Mangler to use.
.SH AUTHOR
This manual page was written by Vincent Cheng <Vincentc1208@gmail.com>,
for the Debian project (and may be used by others).
